const cfg=window.MOVE_HQ_CONFIG||{};const {createClient}=window.supabase||{};let sb,session=null,view='dashboard',data={rooms:[],tasks:[],inventory:[],wishlist:[],moodboard:[],profile:null};let modalType=null,modalId=null;
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const money=n=>`$${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
function msg(t,ok=false){$('authMsg').textContent=t;$('authMsg').style.color=ok?'#2e7d32':'#b42318'}
async function init(){if(!cfg.supabaseUrl||cfg.supabaseUrl.includes('YOUR-')){showAuth();msg('Set your Supabase URL and anon key in config.js.');return}sb=createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);const r=await sb.auth.getSession();session=r.data.session;if(session) await boot(); else showAuth();sb.auth.onAuthStateChange(async(_e,s)=>{session=s;if(s) await boot();else showAuth()})}
function showAuth(){ $('auth').classList.remove('hidden');$('app').classList.add('hidden') }
async function boot(){ $('auth').classList.add('hidden');$('app').classList.remove('hidden');$('userEmail').textContent=session.user.email||'';await loadAll();render() }
async function loadAll(){setSync('Syncing…');const uid=session.user.id;const qs=[['rooms','*'],['tasks','*'],['inventory','*'],['wishlist','*'],['moodboard','*'],['profiles','*']];for(const [table,cols] of qs){const q=await sb.from(table).select(cols).eq(table==='profiles'?'id':'user_id',uid).order('created_at',{ascending:true});if(q.error){setSync('Sync error');console.error(q.error);return}data[table]=q.data||[]}data.profile=data.profiles?.[0]||null;delete data.profiles;setSync('Synced')}
function setSync(t){$('syncStatus').textContent=t}
function render(){const names={dashboard:'Dashboard',tasks:'Tasks',inventory:'Inventory',packing:'Packing',rooms:'Rooms',wishlist:'Wishlist',moodboard:'Moodboard'};$('viewTitle').textContent=names[view];document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('content').innerHTML=({dashboard:dashboard,tasks:tasks,inventory:inventory,packing:packing,rooms:rooms,wishlist:wishlist,moodboard:moodboard}[view])();bindView()}
function dashboard(){const open=data.tasks.filter(x=>!x.done).length,packed=data.inventory.filter(x=>x.status==='Packed').length,total=data.inventory.length,buy=data.wishlist.reduce((a,x)=>a+Number(x.price||0),0),move=data.profile?.move_date;let countdown='—';if(move){const d=Math.ceil((new Date(move+'T00:00:00')-new Date())/86400000);countdown=d<0?`${Math.abs(d)} days ago`:d===0?'Today':`${d} days`}return `<div class="grid stats"><div class="card stat"><div class="label">Open tasks</div><div class="value">${open}</div></div><div class="card stat"><div class="label">Packing</div><div class="value">${total?Math.round(packed/total*100):0}%</div></div><div class="card stat"><div class="label">Wishlist</div><div class="value">${money(buy)}</div></div><div class="card stat"><div class="label">Move date</div><div class="value">${countdown}</div></div></div><div class="section grid" style="grid-template-columns:1.2fr .8fr"><div class="card"><h2>What needs attention</h2>${attention()}</div><div class="card"><h2>Packing progress</h2><p class="muted">${packed} of ${total} inventory items packed</p><div class="bar"><i style="width:${total?packed/total*100:0}%"></i></div><div style="margin-top:18px"><button class="primary" data-add="inventory">Add item</button></div></div></div>`}
function attention(){const t=data.tasks.filter(x=>!x.done).sort((a,b)=>(a.due_date||'9').localeCompare(b.due_date||'9')).slice(0,6);if(!t.length)return '<div class="empty">Nothing urgent right now.</div>';return t.map(x=>`<div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #eee"><span><b>${esc(x.title)}</b><br><small class="muted">${esc(x.category)} · ${x.due_date||'No due date'}</small></span><span class="pill">${esc(x.priority)}</span></div>`).join('')}
function toolbar(placeholder,filter=''){return `<div class="toolbar"><input id="search" placeholder="${placeholder}"><select id="filter"><option value="">All</option>${filter}</select><button class="primary small" data-add="${view==='packing'?'inventory':view}">+ Add</button></div>`}
function tasks(){return toolbar('Search tasks','<option>Open</option><option>Done</option>')+`<div class="tablewrap"><table class="table"><thead><tr><th>Task</th><th>Category</th><th>Due</th><th>Priority</th><th>Status</th><th></th></tr></thead><tbody id="rows">${data.tasks.map(x=>`<tr data-text="${esc(x.title+' '+x.category+' '+x.notes)}" data-status="${x.done?'Done':'Open'}"><td>${esc(x.title)}</td><td>${esc(x.category)}</td><td>${x.due_date||'—'}</td><td><span class="pill">${esc(x.priority)}</span></td><td>${x.done?'Done':'Open'}</td><td class="actions"><button data-edit="tasks:${x.id}">Edit</button><button data-delete="tasks:${x.id}">Delete</button></td></tr>`).join('')}</tbody></table></div>`}
function inventory(){return toolbar('Search inventory','<option>Bring</option><option>Pack</option><option>Sell</option><option>Donate</option><option>Trash</option><option>Replace</option>')+`<div class="tablewrap"><table class="table"><thead><tr><th>Item</th><th>Room</th><th>Action</th><th>Status</th><th>Qty</th><th>Photo</th><th></th></tr></thead><tbody>${data.inventory.map(x=>`<tr data-text="${esc(x.name+' '+(x.notes||''))}" data-status="${esc(x.action)}"><td><b>${esc(x.name)}</b><br><small class="muted">${esc(x.notes||'')}</small></td><td>${roomName(x.room_id)}</td><td><span class="pill">${esc(x.action)}</span></td><td>${esc(x.status)}</td><td>${x.quantity}</td><td>${x.photo_path?'<span class="pill">Photo</span>':'—'}</td><td class="actions"><button data-edit="inventory:${x.id}">Edit</button><button data-delete="inventory:${x.id}">Delete</button></td></tr>`).join('')}</tbody></table></div>`}
function packing(){const grouped={};data.inventory.filter(x=>x.action==='Pack'||x.action==='Bring').forEach(x=>{const r=roomName(x.room_id);(grouped[r]??=[]).push(x)});return `<div class="grid cards">${Object.entries(grouped).map(([r,items])=>{const done=items.filter(x=>x.status==='Packed').length;return `<div class="card"><h2>${esc(r)}</h2><p class="muted">${done}/${items.length} packed</p><div class="bar"><i style="width:${done/items.length*100}%"></i></div><div style="margin-top:14px">${items.map(x=>`<label style="display:block;padding:7px 0"><input type="checkbox" data-pack="${x.id}" ${x.status==='Packed'?'checked':''}> ${esc(x.name)}</label>`).join('')}</div></div>`}).join('')||'<div class="card empty">No packable items yet.</div>'}</div>`}
function rooms(){return `<div class="grid roomgrid">${data.rooms.map(r=>{const items=data.inventory.filter(x=>x.room_id===r.id),wish=data.wishlist.filter(x=>x.room_id===r.id);return `<div class="card"><h2>${esc(r.name)}</h2><p class="muted">${items.length} inventory items · ${wish.length} wishlist items</p><b>Budget ${money(r.budget)}</b><p class="muted">${esc(r.notes||'')}</p><button class="secondary" data-edit="rooms:${r.id}">Edit</button></div>`}).join('')}<div class="card"><button class="primary" data-add="rooms">+ Add room</button></div></div>`}
function wishlist(){return toolbar('Search wishlist','<option>Considering</option><option>Want</option><option>Ordered</option><option>Bought</option><option>Skip</option>')+`<div class="grid cards">${data.wishlist.map(x=>`<div class="card"><div style="display:flex;gap:12px">${x.photo_path?`<img class="thumb" data-photo="${esc(x.photo_path)}">`:'<div class="thumb"></div>'}<div><h2 style="margin:0">${esc(x.name)}</h2><div>${money(x.price)} · ${esc(x.priority)}</div><div class="muted">${roomName(x.room_id)} · ${esc(x.status)}</div></div></div><p class="muted">${esc(x.notes||'')}</p>${x.product_url?`<a href="${esc(x.product_url)}" target="_blank" rel="noopener">Product link</a>`:''}<div class="actions" style="margin-top:12px"><button data-edit="wishlist:${x.id}">Edit</button><button data-delete="wishlist:${x.id}">Delete</button></div></div>`).join('')||'<div class="card empty">Your wishlist is empty.</div>'}</div>`}
function moodboard(){return `<div class="grid cards">${data.moodboard.map(x=>`<div class="card mood">${x.image_path?`<img data-photo="${esc(x.image_path)}">`:x.image_url?`<img src="${esc(x.image_url)}">`:''}<div class="body"><h2>${esc(x.title)}</h2><div class="muted">${roomName(x.room_id)}</div><p>${esc(x.notes||'')}</p><button class="secondary" data-edit="moodboard:${x.id}">Edit</button> <button class="secondary" data-delete="moodboard:${x.id}">Delete</button></div></div>`).join('')}<div class="card empty"><button class="primary" data-add="moodboard">+ Add inspiration</button></div></div>`}
function roomName(id){return data.rooms.find(x=>x.id===id)?.name||'Unassigned'}
function bindView(){const s=$('search'),f=$('filter');if(s){const apply=()=>document.querySelectorAll('#content tbody tr').forEach(r=>r.style.display=(!s.value||r.dataset.text.toLowerCase().includes(s.value.toLowerCase()))&&(!f.value||r.dataset.status===f.value)?'':'none');s.oninput=apply;f.onchange=apply}document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openModal(b.dataset.add));document.querySelectorAll('[data-edit]').forEach(b=>{b.onclick=()=>{const [t,id]=b.dataset.edit.split(':');openModal(t,id)}});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete.split(':')));document.querySelectorAll('[data-pack]').forEach(b=>b.onchange=()=>setPacked(b.dataset.pack,b.checked));document.querySelectorAll('[data-photo]').forEach(async im=>{im.src=await signed(im.dataset.photo)});}
async function setPacked(id,checked){await sb.from('inventory').update({status:checked?'Packed':'Planned',updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',session.user.id);await loadAll();render()}
async function remove([table,id]){if(!confirm('Delete this item?'))return;const r=await sb.from(table).delete().eq('id',id).eq('user_id',session.user.id);if(r.error)alert(r.error.message);await loadAll();render()}
function fields(type,obj={}){const rOpts=data.rooms.map(r=>`<option value="${r.id}" ${obj.room_id===r.id?'selected':''}>${esc(r.name)}</option>`).join('');const commonRoom=`<div class="field"><label>Room</label><select name="room_id"><option value="">Unassigned</option>${rOpts}</select></div>`;if(type==='tasks')return `<div class="formgrid"><div class="field full"><label>Title</label><input name="title" required value="${esc(obj.title)}"></div><div class="field"><label>Category</label><input name="category" value="${esc(obj.category||'Move')}"></div><div class="field"><label>Due date</label><input type="date" name="due_date" value="${obj.due_date||''}"></div><div class="field"><label>Priority</label><select name="priority">${['Low','Medium','High'].map(v=>`<option ${obj.priority===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Status</label><select name="done"><option value="false" ${!obj.done?'selected':''}>Open</option><option value="true" ${obj.done?'selected':''}>Done</option></select></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(obj.notes)}</textarea></div></div>`;
if(type==='rooms')return `<div class="formgrid"><div class="field full"><label>Name</label><input name="name" required value="${esc(obj.name)}"></div><div class="field"><label>Budget</label><input type="number" step="0.01" name="budget" value="${obj.budget||0}"></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(obj.notes)}</textarea></div></div>`;
if(type==='inventory')return `<div class="formgrid"><div class="field full"><label>Item</label><input name="name" required value="${esc(obj.name)}"></div>${commonRoom}<div class="field"><label>Quantity</label><input type="number" name="quantity" min="1" value="${obj.quantity||1}"></div><div class="field"><label>Action</label><select name="action">${['Bring','Pack','Sell','Donate','Trash','Replace'].map(v=>`<option ${obj.action===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Status</label><select name="status">${['Planned','Packed','Done'].map(v=>`<option ${obj.status===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Price</label><input type="number" step="0.01" name="price" value="${obj.price||0}"></div><div class="field full"><label>Product URL</label><input name="product_url" type="url" value="${esc(obj.product_url)}"></div><div class="field full"><label>Photo</label><input class="upload" type="file" name="photo" accept="image/*">${obj.photo_path?'<small>Existing photo will remain unless replaced.</small>':''}</div><div class="field full"><label>Notes</label><textarea name="notes">${esc(obj.notes)}</textarea></div></div>`;
if(type==='wishlist')return `<div class="formgrid"><div class="field full"><label>Product</label><input name="name" required value="${esc(obj.name)}"></div>${commonRoom}<div class="field"><label>Price</label><input type="number" step="0.01" name="price" value="${obj.price||0}"></div><div class="field"><label>Priority</label><select name="priority">${['Must have','Nice to have','Maybe'].map(v=>`<option ${obj.priority===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Status</label><select name="status">${['Considering','Want','Ordered','Bought','Skip'].map(v=>`<option ${obj.status===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field full"><label>Product URL</label><input name="product_url" type="url" value="${esc(obj.product_url)}"></div><div class="field full"><label>Photo</label><input class="upload" type="file" name="photo" accept="image/*"></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(obj.notes)}</textarea></div></div>`;
return `<div class="formgrid"><div class="field full"><label>Title</label><input name="title" required value="${esc(obj.title)}"></div>${commonRoom}<div class="field full"><label>Image URL (optional)</label><input name="image_url" type="url" value="${esc(obj.image_url)}"></div><div class="field full"><label>Upload photo</label><input class="upload" type="file" name="photo" accept="image/*"></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(obj.notes)}</textarea></div></div>`}
function openModal(type,id){modalType=type;modalId=id;const obj=id?(data[type].find(x=>x.id===id)||{}):{};$('modalTitle').textContent=(id?'Edit ':'Add ')+type.replace('moodboard','moodboard item');$('modalForm').innerHTML=fields(type,obj)+`<div class="modal-actions"><button type="button" class="secondary" id="cancel">Cancel</button><button class="primary">Save</button></div>`;$('modal').classList.remove('hidden');$('cancel').onclick=closeModal;$('modalForm').onsubmit=e=>save(e,type,id,obj)}
function closeModal(){$('modal').classList.add('hidden')}
async function upload(file){if(!file)return null;const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${session.user.id}/${crypto.randomUUID()}.${ext}`;const r=await sb.storage.from('move-hq-media').upload(path,file,{upsert:false,contentType:file.type});if(r.error)throw r.error;return path}
async function save(e,type,id,old){e.preventDefault();const fd=new FormData(e.target),o={};for(const [k,v] of fd.entries())if(k!=='photo')o[k]=v;o.user_id=session.user.id;o.updated_at=new Date().toISOString();if(type==='tasks')o.done=o.done==='true';if(['rooms','inventory','wishlist'].includes(type)){if('budget'in o)o.budget=Number(o.budget||0);if('price'in o)o.price=Number(o.price||0);if('quantity'in o)o.quantity=Number(o.quantity||1);if(o.room_id==='')o.room_id=null}const file=fd.get('photo');if(file&&file.size){try{o[type==='moodboard'?'image_path':'photo_path']=await upload(file)}catch(err){alert('Photo upload failed: '+err.message);return}}if(!id)o.created_at=new Date().toISOString();let q;if(id)q=await sb.from(type).update(o).eq('id',id).eq('user_id',session.user.id);else q=await sb.from(type).insert(o);if(q.error){alert(q.error.message);return}closeModal();await loadAll();render()}
async function signed(path){if(!path)return '';const r=await sb.storage.from('move-hq-media').createSignedUrl(path,3600);return r.data?.signedUrl||''}
$('authForm').onsubmit=async e=>{e.preventDefault();msg('');const email=$('authEmail').value.trim(),password=$('authPassword').value;const signUp=$('authTitle').textContent==='Create account';const r=signUp?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});if(r.error)msg(r.error.message);else if(signUp)msg('Account created. Check your email if confirmation is enabled.',true)};
$('toggleAuth').onclick=()=>{const signup=$('authTitle').textContent!=='Create account';$('authTitle').textContent=signup?'Create account':'Sign in';$('authSub').textContent=signup?'Create your cloud-synced Move HQ.':'Your move, packing, and new-home workspace.';$('authForm').querySelector('button').textContent=signup?'Create account':'Sign in';$('toggleAuth').textContent=signup?'Already have an account? Sign in':'Need an account? Sign up'};
$('signOut').onclick=()=>sb.auth.signOut();$('closeModal').onclick=closeModal;$('menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelector('.sidebar').classList.remove('open');render()});$('addBtn').onclick=()=>openModal(view==='packing'?'inventory':view==='dashboard'?'tasks':view);init();
