const cfg=window.MOVE_HQ_CONFIG||{};
const {createClient}=window.supabase||{};
let sb,session=null,view='dashboard',selectedContainer=null;
let data={rooms:[],tasks:[],inventory:[],wishlist:[],moodboard:[],profiles:[],containers:[],contents:[],closet:[]};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=n=>`$${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
const uid=()=>session.user.id;
function msg(t,ok=false){$('authMsg').textContent=t;$('authMsg').style.color=ok?'#2e7d32':'#b42318'}
async function init(){
  if(!cfg.supabaseUrl||cfg.supabaseUrl.includes('YOUR-')){showAuth();msg('Set your Supabase URL and anon key in config.js.');return}
  sb=createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
  const r=await sb.auth.getSession(); session=r.data.session;
  if(session) await boot(); else showAuth();
  sb.auth.onAuthStateChange(async(_e,s)=>{session=s;if(s) await boot();else showAuth()});
}
function showAuth(){$('auth').classList.remove('hidden');$('app').classList.add('hidden')}
async function boot(){$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('userEmail').textContent=session.user.email||'';await loadAll();render()}
async function loadAll(){
  setSync('Syncing…');
  const tables=['rooms','tasks','inventory','wishlist','moodboard','profiles','containers','container_contents','closet_items'];
  for(const table of tables){
    const key=table==='profiles'?'id':'user_id';
    const q=await sb.from(table).select('*').eq(key,uid()).order('created_at',{ascending:true});
    if(q.error){setSync('Sync error');console.error(q.error);return}
    if(table==='container_contents')data.contents=q.data||[];
    else if(table==='closet_items')data.closet=q.data||[];
    else data[table]=q.data||[];
  }
  setSync('Synced');
}
function setSync(t){$('syncStatus').textContent=t}
function render(){
  const names={dashboard:'Dashboard',tasks:'Tasks',inventory:'Inventory',packing:'Packing Helper',closet:'Closet',rooms:'Rooms',wishlist:'Wishlist',moodboard:'Moodboard'};
  $('viewTitle').textContent=names[view];
  document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
  $('content').innerHTML=({dashboard,tasks,inventory,packing,closet,rooms,wishlist,moodboard}[view])();
  bindView();
}
function dashboard(){
  const open=data.tasks.filter(x=>!x.done).length;
  const packed=data.containers.filter(x=>x.status==='Packed'||x.status==='Moved').length;
  const total=data.containers.length;
  const unboxed=data.contents.filter(x=>!x.container_id).length;
  const closetToPack=data.closet.filter(x=>x.status!=='Packed'&&x.keep_action==='Bring').length;
  const buy=data.wishlist.reduce((a,x)=>a+Number(x.price||0),0);
  const move=data.profiles[0]?.move_date;
  let countdown='—'; if(move){const d=Math.ceil((new Date(move+'T00:00:00')-new Date())/86400000);countdown=d<0?`${Math.abs(d)} days ago`:d===0?'Today':`${d} days`}
  return `<div class="grid stats">
    <div class="card stat"><div class="label">Open tasks</div><div class="value">${open}</div></div>
    <div class="card stat"><div class="label">Containers packed</div><div class="value">${packed}/${total}</div></div>
    <div class="card stat"><div class="label">Unassigned contents</div><div class="value">${unboxed}</div></div>
    <div class="card stat"><div class="label">Move date</div><div class="value">${countdown}</div></div>
  </div>
  <div class="section grid" style="grid-template-columns:1.2fr .8fr">
    <div class="card"><h2>What needs attention</h2>${attention()}</div>
    <div class="card"><h2>Packing snapshot</h2><p class="muted">${closetToPack} closet items still need a packing decision.</p><p class="muted">${unboxed} contents are not assigned to a box, suitcase, bag, or other container.</p><button class="primary" data-view-jump="packing">Open packing helper</button></div>
  </div>`
}
function attention(){const t=data.tasks.filter(x=>!x.done).sort((a,b)=>(a.due_date||'9').localeCompare(b.due_date||'9')).slice(0,6);if(!t.length)return '<div class="empty">Nothing urgent right now.</div>';return t.map(x=>`<div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #eee"><span><b>${esc(x.title)}</b><br><small class="muted">${esc(x.category)} · ${x.due_date||'No due date'}</small></span><span class="pill">${esc(x.priority)}</span></div>`).join('')}
function toolbar(placeholder,filter='',addView=view){return `<div class="toolbar"><input id="search" placeholder="${placeholder}"><select id="filter"><option value="">All</option>${filter}</select><button class="primary small" data-add="${addView}">+ Add</button></div>`}
function tasks(){return toolbar('Search tasks','<option>Open</option><option>Done</option>','tasks')+`<div class="tablewrap"><table class="table"><thead><tr><th>Task</th><th>Category</th><th>Due</th><th>Priority</th><th>Status</th><th></th></tr></thead><tbody>${data.tasks.map(x=>`<tr data-text="${esc(x.title+' '+x.category+' '+x.notes)}" data-status="${x.done?'Done':'Open'}"><td>${esc(x.title)}</td><td>${esc(x.category)}</td><td>${x.due_date||'—'}</td><td><span class="pill">${esc(x.priority)}</span></td><td>${x.done?'Done':'Open'}</td><td class="actions"><button data-edit="tasks:${x.id}">Edit</button><button data-delete="tasks:${x.id}">Delete</button></td></tr>`).join('')}</tbody></table></div>`}
function inventory(){return toolbar('Search inventory','<option>Bring</option><option>Pack</option><option>Sell</option><option>Donate</option><option>Trash</option><option>Replace</option>','inventory')+`<div class="tablewrap"><table class="table"><thead><tr><th>Item</th><th>Room</th><th>Action</th><th>Status</th><th>Qty</th><th>Container</th><th></th></tr></thead><tbody>${data.inventory.map(x=>`<tr data-text="${esc(x.name+' '+(x.notes||''))}" data-status="${esc(x.action)}"><td><b>${esc(x.name)}</b><br><small class="muted">${esc(x.notes||'')}</small></td><td>${roomName(x.room_id)}</td><td><span class="pill">${esc(x.action)}</span></td><td>${esc(x.status)}</td><td>${x.quantity}</td><td>${inventoryContainer(x.id)}</td><td class="actions"><button data-edit="inventory:${x.id}">Edit</button><button data-delete="inventory:${x.id}">Delete</button></td></tr>`).join('')}</tbody></table></div>`}
function inventoryContainer(id){const c=data.contents.find(x=>x.inventory_id===id);return c?esc(containerName(c.container_id)):'—'}
function packing(){
  const types={Box:'Boxes',Suitcase:'Suitcases',Bag:'Bags',Bin:'Bins',Other:'Other'};
  const assigned=new Set(data.contents.map(x=>x.container_id));
  const totalContents=data.contents.length, packedContainers=data.containers.filter(x=>x.status==='Packed'||x.status==='Moved').length;
  const active=data.containers.find(x=>x.id===selectedContainer)||data.containers[0];
  if(active)selectedContainer=active.id;
  return `<div class="notice"><b>Packing helper:</b> create your actual containers first, then put the exact contents inside them. For example: <b>Box 1 → Shoes A, Shoes B, Shoes C</b> or <b>Suitcase 1 → books + toiletries</b>. Dimensions and capacity stay with each container.</div>
  <div class="grid stats"><div class="card stat"><div class="label">Containers</div><div class="value">${data.containers.length}</div></div><div class="card stat"><div class="label">Packed</div><div class="value">${packedContainers}</div></div><div class="card stat"><div class="label">Total contents</div><div class="value">${totalContents}</div></div><div class="card stat"><div class="label">Unassigned</div><div class="value">${data.contents.filter(x=>!x.container_id).length}</div></div></div>
  <div class="section" style="display:grid;grid-template-columns:minmax(260px,.7fr) minmax(0,1.3fr);gap:16px">
    <div class="card"><div class="section-head"><h2>My containers</h2><button class="primary small" data-add="containers">+ Container</button></div>${data.containers.length?data.containers.map(c=>{const n=data.contents.filter(x=>x.container_id===c.id).reduce((a,x)=>a+Number(x.quantity||1),0);return `<button class="container-card ${selectedContainer===c.id?'selected':''}" data-select-container="${c.id}"><div><b>${esc(c.name)}</b><span class="pill">${esc(c.type)}</span></div><div class="muted">${n} item${n===1?'':'s'} · ${esc(c.status)}</div><small class="muted">${dimensions(c)}</small></button>`}).join(''):'<div class="empty">No containers yet.</div>'}</div>
    <div class="card">${active?containerDetail(active):'<div class="empty">Select or create a container.</div>'}</div>
  </div>`
}
function containerDetail(c){
  const contents=data.contents.filter(x=>x.container_id===c.id);
  return `<div class="section-head"><div><h2 style="margin:0">${esc(c.name)}</h2><div class="muted">${esc(c.type)} · ${esc(c.status)}</div></div><div class="actions"><button class="secondary" data-edit="containers:${c.id}">Edit</button><button class="secondary" data-delete="containers:${c.id}">Delete</button></div></div>
  <div class="mini-grid"><div><b>Dimensions</b><br>${esc(dimensions(c))}</div><div><b>Weight limit</b><br>${c.weight_limit?esc(c.weight_limit+' '+(c.weight_unit||'lb')):'—'}</div><div><b>Location</b><br>${esc(c.location||'—')}</div><div><b>Notes</b><br>${esc(c.notes||'—')}</div></div>
  <div class="section-head" style="margin-top:20px"><h3 style="margin:0">Contents (${contents.length})</h3><button class="primary small" data-add-content="${c.id}">+ Add content</button></div>
  ${contents.length?`<div class="content-list">${contents.map(x=>`<div class="content-row"><div><b>${esc(x.name)}</b><div class="muted">Qty ${x.quantity||1}${x.source_type&&x.source_type!=='Manual'?' · '+esc(x.source_type):''}${x.notes?' · '+esc(x.notes):''}</div></div><button class="secondary" data-delete-content="${x.id}">Remove</button></div>`).join('')}</div>`:'<div class="empty">Nothing packed in this container yet.</div>'}`
}
function closet(){
  const bring=data.closet.filter(x=>x.keep_action==='Bring');
  const packed=bring.filter(x=>x.status==='Packed').length;
  return `<div class="notice"><b>Closet:</b> keep a living inventory of clothes, shoes, bags, and accessories. Decide what comes with you, what gets sold/donated, and exactly which container each item goes into.</div>
  <div class="grid stats"><div class="card stat"><div class="label">Closet items</div><div class="value">${data.closet.length}</div></div><div class="card stat"><div class="label">Bring</div><div class="value">${bring.length}</div></div><div class="card stat"><div class="label">Packed</div><div class="value">${packed}</div></div><div class="card stat"><div class="label">Need decision</div><div class="value">${data.closet.filter(x=>x.keep_action==='Decide').length}</div></div></div>
  ${toolbar('Search closet','<option>Bring</option><option>Sell</option><option>Donate</option><option>Decide</option><option>Trash</option>','closet')}
  <div class="tablewrap"><table class="table"><thead><tr><th>Item</th><th>Category</th><th>Season</th><th>Decision</th><th>Status</th><th>Container</th><th></th></tr></thead><tbody>${data.closet.map(x=>`<tr data-text="${esc(x.name+' '+x.category+' '+x.season+' '+(x.notes||''))}" data-status="${esc(x.keep_action)}"><td><b>${esc(x.name)}</b><br><small class="muted">Qty ${x.quantity||1}</small></td><td>${esc(x.category)}</td><td>${esc(x.season||'All')}</td><td><span class="pill">${esc(x.keep_action)}</span></td><td>${esc(x.status)}</td><td>${x.container_id?esc(containerName(x.container_id)):'—'}</td><td class="actions"><button data-edit="closet:${x.id}">Edit</button><button data-delete="closet:${x.id}">Delete</button></td></tr>`).join('')}</tbody></table></div>`
}
function rooms(){return `<div class="grid roomgrid">${data.rooms.map(r=>{const items=data.inventory.filter(x=>x.room_id===r.id),wish=data.wishlist.filter(x=>x.room_id===r.id);return `<div class="card"><h2>${esc(r.name)}</h2><p class="muted">${items.length} inventory items · ${wish.length} wishlist items</p><b>Budget ${money(r.budget)}</b><p class="muted">${esc(r.notes||'')}</p><button class="secondary" data-edit="rooms:${r.id}">Edit</button></div>`}).join('')}<div class="card"><button class="primary" data-add="rooms">+ Add room</button></div></div>`}
function wishlist(){return toolbar('Search wishlist','<option>Considering</option><option>Want</option><option>Ordered</option><option>Bought</option><option>Skip</option>','wishlist')+`<div class="grid cards">${data.wishlist.map(x=>`<div class="card"><div style="display:flex;gap:12px">${x.photo_path?`<img class="thumb" data-photo="${esc(x.photo_path)}">`:'<div class="thumb"></div>'}<div><h2 style="margin:0">${esc(x.name)}</h2><div>${money(x.price)} · ${esc(x.priority)}</div><div class="muted">${roomName(x.room_id)} · ${esc(x.status)}</div></div></div><p class="muted">${esc(x.notes||'')}</p>${x.product_url?`<a href="${esc(x.product_url)}" target="_blank" rel="noopener">Product link</a>`:''}<div class="actions" style="margin-top:12px"><button data-edit="wishlist:${x.id}">Edit</button><button data-delete="wishlist:${x.id}">Delete</button></div></div>`).join('')||'<div class="card empty">Your wishlist is empty.</div>'}</div>`}
function moodboard(){return `<div class="grid cards">${data.moodboard.map(x=>`<div class="card mood">${x.image_path?`<img data-photo="${esc(x.image_path)}">`:x.image_url?`<img src="${esc(x.image_url)}">`:''}<div class="body"><h2>${esc(x.title)}</h2><div class="muted">${roomName(x.room_id)}</div><p>${esc(x.notes||'')}</p><button class="secondary" data-edit="moodboard:${x.id}">Edit</button> <button class="secondary" data-delete="moodboard:${x.id}">Delete</button></div></div>`).join('')}<div class="card empty"><button class="primary" data-add="moodboard">+ Add inspiration</button></div></div>`}
function roomName(id){return data.rooms.find(x=>x.id===id)?.name||'Unassigned'}
function containerName(id){return data.containers.find(x=>x.id===id)?.name||'Unassigned'}
function dimensions(c){if(!c.length&&!c.width&&!c.height)return 'No dimensions';return [c.length,c.width,c.height].map(v=>v||'—').join(' × ')+' '+(c.dimension_unit||'in')}
function bindView(){
  const s=$('search'),f=$('filter');
  if(s){const apply=()=>document.querySelectorAll('#content tbody tr').forEach(r=>r.style.display=(!s.value||r.dataset.text.toLowerCase().includes(s.value.toLowerCase()))&&(!f.value||r.dataset.status===f.value)?'':'none');s.oninput=apply;f.onchange=apply}
  document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openModal(b.dataset.add));
  document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const [t,id]=b.dataset.edit.split(':');openModal(t,id)});
  document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete.split(':')));
  document.querySelectorAll('[data-add-content]').forEach(b=>b.onclick=()=>openContentModal(b.dataset.addContent));
  document.querySelectorAll('[data-delete-content]').forEach(b=>b.onclick=()=>removeContent(b.dataset.deleteContent));
  document.querySelectorAll('[data-select-container]').forEach(b=>b.onclick=()=>{selectedContainer=b.dataset.selectContainer;render()});
  document.querySelectorAll('[data-view-jump]').forEach(b=>b.onclick=()=>{view=b.dataset.viewJump;render()});
  document.querySelectorAll('[data-photo]').forEach(async im=>{im.src=await signed(im.dataset.photo)});
}
async function remove([table,id]){if(!confirm('Delete this item?'))return;const dbTable=table==='closet'?'closet_items':table;const r=await sb.from(dbTable).delete().eq('id',id).eq('user_id',uid());if(r.error)alert(r.error.message);if(table==='containers'&&selectedContainer===id)selectedContainer=null;await loadAll();render()}
async function removeContent(id){if(!confirm('Remove this content from the container?'))return;const r=await sb.from('container_contents').delete().eq('id',id).eq('user_id',uid());if(r.error)alert(r.error.message);await loadAll();render()}
function roomOptions(selected){return data.rooms.map(r=>`<option value="${r.id}" ${selected===r.id?'selected':''}>${esc(r.name)}</option>`).join('')}
function containerOptions(selected){return data.containers.map(r=>`<option value="${r.id}" ${selected===r.id?'selected':''}>${esc(r.name)}</option>`).join('')}
function fields(type,obj={}){
  const commonRoom=`<div class="field"><label>Room</label><select name="room_id"><option value="">Unassigned</option>${roomOptions(obj.room_id)}</select></div>`;
  if(type==='tasks')return `<div class="formgrid"><div class="field full"><label>Title</label><input name="title" required value="${esc(obj.title)}"></div><div class="field"><label>Category</label><input name="category" value="${esc(obj.category||'Move')}"></div><div class="field"><label>Due date</label><input type="date" name="due_date" value="${obj.due_date||''}"></div><div class="field"><label>Priority</label><select name="priority">${['Low','Medium','High'].map(v=>`<option ${obj.priority===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Status</label><select name="done"><option value="false" ${!obj.done?'selected':''}>Open</option><option value="true" ${obj.done?'selected':''}>Done</option></select></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(obj.notes)}</textarea></div></div>`;
  if(type==='rooms')return `<div class="formgrid"><div class="field full"><label>Name</label><input name="name" required value="${esc(obj.name)}"></div><div class="field"><label>Budget</label><input type="number" step="0.01" name="budget" value="${obj.budget||0}"></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(obj.notes)}</textarea></div></div>`;
  if(type==='inventory')return `<div class="formgrid"><div class="field full"><label>Item</label><input name="name" required value="${esc(obj.name)}"></div>${commonRoom}<div class="field"><label>Quantity</label><input type="number" name="quantity" min="1" value="${obj.quantity||1}"></div><div class="field"><label>Action</label><select name="action">${['Bring','Pack','Sell','Donate','Trash','Replace'].map(v=>`<option ${obj.action===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Status</label><select name="status">${['Planned','Packed','Done'].map(v=>`<option ${obj.status===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Price</label><input type="number" step="0.01" name="price" value="${obj.price||0}"></div><div class="field full"><label>Product URL</label><input name="product_url" type="url" value="${esc(obj.product_url)}"></div><div class="field full"><label>Photo</label><input class="upload" type="file" name="photo" accept="image/*"></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(obj.notes)}</textarea></div></div>`;
  if(type==='wishlist')return `<div class="formgrid"><div class="field full"><label>Product</label><input name="name" required value="${esc(obj.name)}"></div>${commonRoom}<div class="field"><label>Price</label><input type="number" step="0.01" name="price" value="${obj.price||0}"></div><div class="field"><label>Priority</label><select name="priority">${['Must have','Nice to have','Maybe'].map(v=>`<option ${obj.priority===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Status</label><select name="status">${['Considering','Want','Ordered','Bought','Skip'].map(v=>`<option ${obj.status===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field full"><label>Product URL</label><input name="product_url" type="url" value="${esc(obj.product_url)}"></div><div class="field full"><label>Photo</label><input class="upload" type="file" name="photo" accept="image/*"></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(obj.notes)}</textarea></div></div>`;
  if(type==='containers')return `<div class="formgrid"><div class="field full"><label>Container name</label><input name="name" required placeholder="Box 1, Suitcase 1…" value="${esc(obj.name)}"></div><div class="field"><label>Type</label><select name="type">${['Box','Suitcase','Bag','Bin','Other'].map(v=>`<option ${obj.type===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Status</label><select name="status">${['Planned','Packing','Packed','Moved'].map(v=>`<option ${obj.status===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Length</label><input type="number" step="0.1" name="length" value="${obj.length||''}"></div><div class="field"><label>Width</label><input type="number" step="0.1" name="width" value="${obj.width||''}"></div><div class="field"><label>Height</label><input type="number" step="0.1" name="height" value="${obj.height||''}"></div><div class="field"><label>Dimension unit</label><select name="dimension_unit">${['in','cm'].map(v=>`<option ${obj.dimension_unit===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Weight limit</label><input type="number" step="0.1" name="weight_limit" value="${obj.weight_limit||''}"></div><div class="field"><label>Weight unit</label><select name="weight_unit">${['lb','kg'].map(v=>`<option ${obj.weight_unit===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field full"><label>Location</label><input name="location" placeholder="Closet, bedroom floor, storage unit…" value="${esc(obj.location)}"></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(obj.notes)}</textarea></div></div>`;
  if(type==='closet')return `<div class="formgrid"><div class="field full"><label>Item</label><input name="name" required placeholder="Black boots, winter coat…" value="${esc(obj.name)}"></div><div class="field"><label>Category</label><select name="category">${['Tops','Bottoms','Dresses','Outerwear','Shoes','Bags','Accessories','Underwear','Activewear','Formal','Other'].map(v=>`<option ${obj.category===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Quantity</label><input type="number" min="1" name="quantity" value="${obj.quantity||1}"></div><div class="field"><label>Season</label><select name="season">${['All','Spring','Summer','Fall','Winter'].map(v=>`<option ${obj.season===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Decision</label><select name="keep_action">${['Bring','Sell','Donate','Decide','Trash'].map(v=>`<option ${obj.keep_action===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Packing status</label><select name="status">${['Planned','Packed','Moved'].map(v=>`<option ${obj.status===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Container</label><select name="container_id"><option value="">Not assigned</option>${containerOptions(obj.container_id)}</select></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(obj.notes)}</textarea></div></div>`;
  return `<div class="formgrid"><div class="field full"><label>Title</label><input name="title" required value="${esc(obj.title)}"></div>${commonRoom}<div class="field full"><label>Image URL (optional)</label><input name="image_url" type="url" value="${esc(obj.image_url)}"></div><div class="field full"><label>Upload photo</label><input class="upload" type="file" name="photo" accept="image/*"></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(obj.notes)}</textarea></div></div>`;
}
function openModal(type,id){const obj=id?(data[type==='containers'?'containers':type].find(x=>x.id===id)||{}):{};$('modalTitle').textContent=(id?'Edit ':'Add ')+({containers:'container',closet:'closet item',moodboard:'moodboard item'}[type]||type);$('modalForm').innerHTML=fields(type,obj)+`<div class="modal-actions"><button type="button" class="secondary" id="cancel">Cancel</button><button class="primary">Save</button></div>`;$('modal').classList.remove('hidden');$('cancel').onclick=closeModal;$('modalForm').onsubmit=e=>save(e,type,id)}
function openContentModal(containerId,existingId){const obj=existingId?data.contents.find(x=>x.id===existingId)||{}:{};$('modalTitle').textContent=existingId?'Edit content':'Add content to '+containerName(containerId);$('modalForm').innerHTML=contentFields(containerId,obj)+`<div class="modal-actions"><button type="button" class="secondary" id="cancel">Cancel</button><button class="primary">Save</button></div>`;$('modal').classList.remove('hidden');$('cancel').onclick=closeModal;$('modalForm').onsubmit=e=>saveContent(e,containerId,existingId)}
function contentFields(containerId,obj={}){const inv=data.inventory.filter(x=>x.action==='Bring'||x.action==='Pack');const cl=data.closet.filter(x=>x.keep_action==='Bring');return `<div class="formgrid"><div class="field"><label>Source</label><select name="source_type" id="contentSource"><option ${obj.source_type==='Manual'||!obj.source_type?'selected':''}>Manual</option><option ${obj.source_type==='Inventory'?'selected':''}>Inventory</option><option ${obj.source_type==='Closet'?'selected':''}>Closet</option></select></div><div class="field"><label>Quantity</label><input type="number" min="1" name="quantity" value="${obj.quantity||1}"></div><div class="field full"><label>Existing item (optional)</label><select name="source_id" id="sourceId"><option value="">Choose an item…</option>${inv.map(x=>`<option value="inventory:${x.id}" ${obj.inventory_id===x.id?'selected':''}>Inventory · ${esc(x.name)}</option>`).join('')}${cl.map(x=>`<option value="closet:${x.id}" ${obj.closet_item_id===x.id?'selected':''}>Closet · ${esc(x.name)}</option>`).join('')}</select></div><div class="field full"><label>Content name</label><input name="name" required placeholder="Shoes A, Toiletries, Books…" value="${esc(obj.name)}"></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(obj.notes)}</textarea></div><input type="hidden" name="container_id" value="${esc(containerId)}"></div>`}
function closeModal(){$('modal').classList.add('hidden')}
async function upload(file){if(!file)return null;const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${uid()}/${crypto.randomUUID()}.${ext}`;const r=await sb.storage.from('move-hq-media').upload(path,file,{upsert:false,contentType:file.type});if(r.error)throw r.error;return path}
async function save(e,type,id){e.preventDefault();const fd=new FormData(e.target),o={};for(const [k,v] of fd.entries())if(k!=='photo')o[k]=v;o.user_id=uid();o.updated_at=new Date().toISOString();if(!id)o.created_at=new Date().toISOString();if(type==='tasks')o.done=o.done==='true';if(['rooms','inventory','wishlist','containers','closet'].includes(type)){for(const k of ['budget','price','length','width','height','weight_limit','quantity'])if(k in o)o[k]=o[k]===''?null:Number(o[k]);if('room_id'in o&&o.room_id==='')o.room_id=null;if('container_id'in o&&o.container_id==='')o.container_id=null}if(type==='moodboard'){const file=fd.get('photo');if(file&&file.size)try{o.image_path=await upload(file)}catch(err){alert('Photo upload failed: '+err.message);return}}
  if(['inventory','wishlist'].includes(type)){const file=fd.get('photo');if(file&&file.size)try{o.photo_path=await upload(file)}catch(err){alert('Photo upload failed: '+err.message);return}}
  const table=type==='containers'?'containers':type==='closet'?'closet_items':type;
  const q=id?await sb.from(table).update(o).eq('id',id).eq('user_id',uid()):await sb.from(table).insert(o);
  if(q.error){alert(q.error.message);return}closeModal();await loadAll();render()}
async function saveContent(e,containerId,id){e.preventDefault();const fd=new FormData(e.target);const source=String(fd.get('source_id')||'');const o={user_id:uid(),container_id:containerId,name:String(fd.get('name')||'').trim(),quantity:Number(fd.get('quantity')||1),notes:fd.get('notes')||'',source_type:fd.get('source_type')||'Manual',updated_at:new Date().toISOString()};if(source.startsWith('inventory:')){o.inventory_id=source.split(':')[1];o.source_type='Inventory'}else if(source.startsWith('closet:')){o.closet_item_id=source.split(':')[1];o.source_type='Closet'}else{o.inventory_id=null;o.closet_item_id=null}if(!o.name){alert('Add a content name.');return}if(!id)o.created_at=new Date().toISOString();const q=id?await sb.from('container_contents').update(o).eq('id',id).eq('user_id',uid()):await sb.from('container_contents').insert(o);if(q.error){alert(q.error.message);return}closeModal();await loadAll();render()}
async function signed(path){if(!path)return '';const r=await sb.storage.from('move-hq-media').createSignedUrl(path,3600);return r.data?.signedUrl||''}
$('authForm').onsubmit=async e=>{e.preventDefault();msg('');const email=$('authEmail').value.trim(),password=$('authPassword').value;const signUp=$('authTitle').textContent==='Create account';const r=signUp?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});if(r.error)msg(r.error.message);else if(signUp)msg('Account created. Check your email if confirmation is enabled.',true)};
$('toggleAuth').onclick=()=>{const signup=$('authTitle').textContent!=='Create account';$('authTitle').textContent=signup?'Create account':'Sign in';$('authSub').textContent=signup?'Create your cloud-synced Move HQ.':'Your move, packing, and new-home workspace.';$('authForm').querySelector('button').textContent=signup?'Create account':'Sign in';$('toggleAuth').textContent=signup?'Already have an account? Sign in':'Need an account? Sign up'};
$('signOut').onclick=()=>sb.auth.signOut();$('closeModal').onclick=closeModal;$('menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;selectedContainer=null;document.querySelector('.sidebar').classList.remove('open');render()});$('addBtn').onclick=()=>openModal(view==='packing'?'containers':view==='dashboard'?'tasks':view);init();
